#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""
Sentinel Action Mapper — CEO-085
Scans the zenzic-action repository and updates the [CODE MAP] section
in .github/copilot-instructions.md between <!-- MAP_START --> and <!-- MAP_END -->.

This repo has no Python src/ — it maps the shell wrapper and YAML manifest.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
LEDGER = REPO_ROOT / "ZENZIC_BRAIN.md"
SHADOW = REPO_ROOT / ".github" / "copilot-instructions.md"
ACTION_YML = REPO_ROOT / "action.yml"
WRAPPER = REPO_ROOT / "zenzic-action-wrapper.sh"

MAP_START = "<!-- MAP_START -->"
MAP_END = "<!-- MAP_END -->"


def _parse_action_yml() -> dict:
    """Extracts inputs and outputs from action.yml without a YAML dependency."""
    if not ACTION_YML.exists():
        return {"inputs": [], "outputs": []}

    text = ACTION_YML.read_text(encoding="utf-8")

    # Locate inputs: and outputs: blocks by line scanning
    inputs: list[tuple[str, str, str]] = []   # (name, description, default)
    outputs: list[tuple[str, str]] = []       # (name, description)

    in_inputs = False
    in_outputs = False
    current_key = None
    current_desc = ""
    current_default = ""

    def _flush():
        """Saves the current pending key to the correct list."""
        if current_key:
            if in_inputs:
                inputs.append((current_key, current_desc, current_default))
            elif in_outputs:
                outputs.append((current_key, current_desc))

    for line in text.splitlines():
        stripped = line.strip()
        if stripped == "inputs:":
            _flush()
            in_inputs, in_outputs = True, False
            current_key = None
            continue
        if stripped == "outputs:":
            _flush()
            in_inputs, in_outputs = False, True
            current_key = None
            continue
        if re.match(r"^[a-zA-Z]", line) and ":" in line and not line.startswith(" "):
            _flush()
            in_inputs = in_outputs = False
            current_key = None
            continue

        if in_inputs or in_outputs:
            # Top-level key under inputs/outputs (2-space indent)
            m_key = re.match(r"^  ([a-zA-Z_-]+):$", line)
            if m_key:
                _flush()
                current_key = m_key.group(1)
                current_desc = ""
                current_default = ""
                continue
            m_desc = re.match(r"^\s+description:\s+'?(.+?)'?\s*$", line)
            if m_desc:
                current_desc = m_desc.group(1).strip("'\"")
            m_def = re.match(r"^\s+default:\s+'?(.+?)'?\s*$", line)
            if m_def:
                current_default = m_def.group(1).strip("'\"")

    _flush()

    return {"inputs": inputs, "outputs": outputs}


def _parse_wrapper_steps() -> list[str]:
    """Extracts numbered step comments from the shell wrapper."""
    if not WRAPPER.exists():
        return []
    steps = []
    for line in WRAPPER.read_text(encoding="utf-8").splitlines():
        m = re.match(r"#\s*(\d+)\.\s+(.+)", line)
        if m:
            steps.append(f"{m.group(1)}. {m.group(2).strip()}")
    return steps


def build_action_map() -> str:
    """Builds the Markdown [CODE MAP] block for the action repo."""
    parsed = _parse_action_yml()
    steps = _parse_wrapper_steps()

    lines = [
        "## [CODE MAP] — Action Structure",
        "",
        "> Auto-generated by `scripts/map_action.py` via static analysis.",
        "> Update with `just map-update` after changing action.yml or the wrapper script.",
        "",
        "### Key Files",
        "",
        "| File | Role |",
        "|------|------|",
        "| `action.yml` | GitHub Action manifest — declares inputs, outputs, composite steps |",
        "| `zenzic-action-wrapper.sh` | Core execution layer — builds uvx command, handles exit codes |",
        "| `scripts/bump-version.sh` | Version bump automation |",
        "",
    ]

    # Inputs table
    if parsed["inputs"]:
        lines.append("### Action Inputs")
        lines.append("")
        lines.append("| Input | Default | Description |")
        lines.append("|-------|---------|-------------|")
        for name, desc, default in parsed["inputs"]:
            lines.append(f"| `{name}` | `{default}` | {desc} |")
        lines.append("")

    # Outputs table
    if parsed["outputs"]:
        lines.append("### Action Outputs")
        lines.append("")
        lines.append("| Output | Description |")
        lines.append("|--------|-------------|")
        for name, desc in parsed["outputs"]:
            lines.append(f"| `{name}` | {desc} |")
        lines.append("")

    # Wrapper execution steps
    if steps:
        lines.append("### Wrapper Execution Flow")
        lines.append("")
        for step in steps:
            lines.append(f"- {step}")
        lines.append("")

    return "\n".join(lines)


def update_ledger(action_map: str) -> None:
    """Replaces the block between MAP_START and MAP_END in the ledger."""
    text = LEDGER.read_text(encoding="utf-8")
    start_idx = text.find(MAP_START)
    end_idx = text.find(MAP_END)

    if start_idx == -1 or end_idx == -1:
        print(
            f"[ERROR] Tags {MAP_START!r} or {MAP_END!r} not found in {LEDGER}.\n"
            "Add the tags to ZENZIC_BRAIN.md before running map-update.",
            file=sys.stderr,
        )
        sys.exit(1)

    new_block = f"{MAP_START}\n{action_map}\n{MAP_END}"
    new_text = text[:start_idx] + new_block + text[end_idx + len(MAP_END):]
    LEDGER.write_text(new_text, encoding="utf-8")
    print(f"[ACTION MAP] updated in {LEDGER.name}")


def shadow_sync() -> None:
    """Copies ZENZIC_BRAIN.md → .github/copilot-instructions.md for IDE compatibility."""
    content = LEDGER.read_text(encoding="utf-8")
    SHADOW.parent.mkdir(parents=True, exist_ok=True)
    SHADOW.write_text(content, encoding="utf-8")
    print(f"[SHADOW] {SHADOW.relative_to(REPO_ROOT)} synced from {LEDGER.name}")


def main() -> None:
    action_map = build_action_map()
    update_ledger(action_map)
    shadow_sync()
    n_inputs = action_map.count("\n| `") - 1  # subtract output rows approx
    print(f"[OK] Action map generated.")


if __name__ == "__main__":
    main()
